[package]
name = "frontend"
version = "0.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = "0.8"
strum = "0.20"
strum_macros = "0.20"

[dependencies.seed-bootstrap]
path = "../.."

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Os']
